mkdir -p results/cifar100

# Pareto N=100, K=10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K10 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K10 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K10 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Pareto N=100, K=20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K20 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K20 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K20 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Pareto N=100, K=30
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K30 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K30 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_pareto_N100_K30 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/pareto/CIFAR-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0


# =============================================================================================================================================================================================================================================================================================================================================================================================================
# quantitative N=100, K=10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K10 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K10 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K10 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# quantitative N=100, K=20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K20 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K20 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K20 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# quantitative N=100, K=30
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K30 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K30 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_quantitative_N100_K30 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/quantitative/CIFAR-noniid-quantitative_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0


# =============================================================================================================================================================================================================================================================================================================================================================================================================
# featured N=100, K=10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K10 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K10 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K10 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# featured N=100, K=20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K20 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K20 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K20 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# featured N=100, K=30
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K30 --model resnet9 --algorithm scaffold --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K30 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar100_featured_N100_K30 --model resnet9 --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/cifar100/data" --log_folder "results/cifar100" --dataidx_filename "cifar100/100client/featured/CIFAR-noniid-featured_1.json" --num_rounds 1000 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
