mkdir fedtask

# cifar10_resnet9_clustered_N10_K10 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR_10client_quantitative.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0


# cifar10_resnet9_clustered_N10_K2 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0


# cifar10_resnet9_clustered_N10_K4 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.2 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.4 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.6 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 0.8 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 3 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 4 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 6 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 7 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 8 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 9 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 10 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0


# cifar10_resnet9_clustered_N10_K6 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# cifar10_resnet9_clustered_N10_K8 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm fedtest --neg_fct 1 --neg_mrg 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar/100client/cluster/CIFAR_100client_quantitative_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
