mkdir fedtask

# # mnist_clustered_N10_K10 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.2 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.2 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.2 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.2 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.5 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.5 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.5 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.5 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.8 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.8 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.8 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_pareto_N10_K10 --dirty_rate 0.8 --noise_magnitude 3 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/pareto/MNIST-noniid-fedavg_pareto_1.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# iid
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.02 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.04 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.06 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.08 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.02 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.04 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.06 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.08 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.9 --noise_magnitude 0.02 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.9 --noise_magnitude 0.04 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.9 --noise_magnitude 0.06 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.9 --noise_magnitude 0.08 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 1.0 --wandb 0 --noise_magnitude 0.02 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 0 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 1.0 --noise_magnitude 0.04 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 1.0 --noise_magnitude 0.06 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 1.0 --noise_magnitude 0.08 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
