# mkdir fedtask

# # mnist_clustered_N10_K10 - quantitative
CUDA_VISIBLE_DEVICES=1,0 python main.py  --task dirtycifar10_iid_N10_K10_00_100 --dirty_rate 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 --noise_magnitude 2 --algorithm mp_fedavg --model resnet18 --data_folder "./benchmark/cifar10/data" --log_folder fedtask --dataidx_filename "cifar10/iid/cifar10_iid_10client.json" --num_rounds 100 --num_epochs 5 --proportion 1 --num_epochs_round_0 5 --batch_size 64 --num_threads_per_gpu 5  --num_gpus 2 --server_gpu_id 0 --wandb 1 --result_file_name check_uncertainty_converge_2.json --uncertainty 1 --file_log_per_epoch check_uncertainty_converge_2.csv --file_save_model check_uncertainty_converge_2 --percent_noise_remove 0
CUDA_VISIBLE_DEVICES=1,0 python main.py  --task dirtycifar10_iid_N10_K10_00_100 --dirty_rate 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 --noise_magnitude 2 --algorithm mp_fedavg --model resnet18 --data_folder "./benchmark/cifar10/data" --log_folder fedtask --dataidx_filename "cifar10/iid/cifar10_iid_10client.json" --num_rounds 20 --num_epochs 5 --proportion 1 --num_epochs_round_0 5 --batch_size 64 --num_threads_per_gpu 5  --num_gpus 2 --server_gpu_id 0 --wandb 1 --result_file_name after_uncertainty_converge_remove_10%_2.json --uncertainty 1 --file_log_per_epoch after_uncertainty_converge_remove_10%_2.csv --file_save_model after_uncertainty_converge_remove_10%_2 --percent_noise_remove 0.1
CUDA_VISIBLE_DEVICES=1,0 python main.py  --task dirtycifar10_iid_N10_K10_00_100 --dirty_rate 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 --noise_magnitude 2 --algorithm mp_fedavg --model resnet18 --data_folder "./benchmark/cifar10/data" --log_folder fedtask --dataidx_filename "cifar10/iid/cifar10_iid_10client.json" --num_rounds 20 --num_epochs 5 --proportion 1 --num_epochs_round_0 5 --batch_size 64 --num_threads_per_gpu 5  --num_gpus 2 --server_gpu_id 0 --wandb 1 --result_file_name after_uncertainty_converge_remove_25%_2.json --uncertainty 1 --file_log_per_epoch after_uncertainty_converge_remove_25%_2.csv --file_save_model after_uncertainty_converge_remove_25%_2 --percent_noise_remove 0.25
CUDA_VISIBLE_DEVICES=1,0 python main.py  --task dirtycifar10_iid_N10_K10_00_100 --dirty_rate 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 --noise_magnitude 2 --algorithm mp_fedavg --model resnet18 --data_folder "./benchmark/cifar10/data" --log_folder fedtask --dataidx_filename "cifar10/iid/cifar10_iid_10client.json" --num_rounds 20 --num_epochs 5 --proportion 1 --num_epochs_round_0 5 --batch_size 64 --num_threads_per_gpu 5  --num_gpus 2 --server_gpu_id 0 --wandb 1 --result_file_name after_uncertainty_converge_remove_50%_2.json --uncertainty 1 --file_log_per_epoch after_uncertainty_converge_remove_50%_2.csv --file_save_model after_uncertainty_converge_remove_50%_2 --percent_noise_remove 0.5
CUDA_VISIBLE_DEVICES=1,0 python main.py  --task dirtycifar10_iid_N10_K10_00_100 --dirty_rate 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 --noise_magnitude 2 --algorithm mp_fedavg --model resnet18 --data_folder "./benchmark/cifar10/data" --log_folder fedtask --dataidx_filename "cifar10/iid/cifar10_iid_10client.json" --num_rounds 20 --num_epochs 5 --proportion 1 --num_epochs_round_0 5 --batch_size 64 --num_threads_per_gpu 5  --num_gpus 2 --server_gpu_id 0 --wandb 1 --result_file_name after_uncertainty_converge_remove_75%_2.json --uncertainty 1 --file_log_per_epoch after_uncertainty_converge_remove_75%_2.csv --file_save_model after_uncertainty_converge_remove_75%_2 --percent_noise_remove 0.75
CUDA_VISIBLE_DEVICES=1,0 python main.py  --task dirtycifar10_iid_N10_K10_00_100 --dirty_rate 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 --noise_magnitude 2 --algorithm mp_fedavg --model resnet18 --data_folder "./benchmark/cifar10/data" --log_folder fedtask --dataidx_filename "cifar10/iid/cifar10_iid_10client.json" --num_rounds 20 --num_epochs 5 --proportion 1 --num_epochs_round_0 5 --batch_size 64 --num_threads_per_gpu 5  --num_gpus 2 --server_gpu_id 0 --wandb 1 --result_file_name after_uncertainty_converge_remove_100%_2.json --uncertainty 1 --file_log_per_epoch after_uncertainty_converge_remove_100%_2.csv --file_save_model after_uncertainty_converge_remove_100%_2 --percent_noise_remove 1.0
