mkdir fedtask

# mnist_clustered_N10_K10 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.2 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.4 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.6 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 0.8 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.2 --noise_magnitude 1.0 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.2 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.4 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.6 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 0.8 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py  --task dirtymnist_N10_K10 --dirty_rate 0.5 --noise_magnitude 1.0 --algorithm mp_fedavg --model cnn --data_folder "./benchmark/mnist/data" --log_folder fedtask --dataidx_filename "mnist/10iid/mnistiid_10client.json" --num_rounds 200 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
