mkdir -p results/fashionmnist

# Pareto N=100, K=10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K10 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K10 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K10 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Pareto N=100, K=20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K20 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K20 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K20 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Pareto N=100, K=30
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K30 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K30 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_pareto_N100_K30 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/pareto/FashionMNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0


# =============================================================================================================================================================================================================================================================================================================================================================================================================
# quantitative N=100, K=10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K10 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K10 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K10 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# quantitative N=100, K=20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K20 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K20 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K20 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# quantitative N=100, K=30
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K30 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K30 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_quantitative_N100_K30 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/quantitative/bias_sample/FashionMNIST-noniid-quantitative_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0


# =============================================================================================================================================================================================================================================================================================================================================================================================================
# featured N=100, K=10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K10 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K10 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K10 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# featured N=100, K=20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K20 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K20 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K20 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# featured N=100, K=30
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K30 --model lr --algorithm scaffold --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K30 --model lr --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task fmnist_featured_N100_K30 --model lr --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/fashion_mnist/data" --log_folder "results/fashionmnist" --dataidx_filename "fashionmnist/100client/featured/bias_sample/FashionMNIST-noniid-featured_bias_sample_1.json" --num_rounds 500 --num_epochs 8 --proportion 0.3 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
