CUDA_VISIBLE_DEVICES=0 /home/admin/miniconda3/envs/easyFL/bin/python main.py --task cifar10_cnn_PA_0.5_N100_K10 --model cnn --algorithm fedfa --wandb 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "journal/cifar10/pareto_0.5/100client" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0 /home/admin/miniconda3/envs/easyFL/bin/python main.py --task cifar10_cnn_BC_NC5_N100_K10 --model cnn --algorithm fedfa --wandb 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "journal/cifar10/uc1_nc5/100client" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0 /home/admin/miniconda3/envs/easyFL/bin/python main.py --task cifar10_cnn_UC_NC5_N100_K10 --model cnn --algorithm fedfa --wandb 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "journal/cifar10/uc4_nc5/100client" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0





# CUDA_VISIBLE_DEVICES=2 python main.py --task mnist_cnn_UC1_N100_K10_NEW --model cnn --algorithm fedavg --wandb 1 --data_folder "./benchmark/mnist/data" --log_folder "fedtask" --dataidx_filename "CADIS/mnist/unbalanced_cluster1/100client" --num_rounds 3000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=2 python main.py --task mnist_cnn_UC5_N100_K10_NEW --model cnn --algorithm fedavg --wandb 1 --data_folder "./benchmark/mnist/data" --log_folder "fedtask" --dataidx_filename "CADIS/mnist/unbalanced_cluster5/100client" --num_rounds 3000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=2 python main.py --task mnist_cnn_UC10_N100_K10_NEW --model cnn --algorithm fedavg --wandb 1 --data_folder "./benchmark/mnist/data" --log_folder "fedtask" --dataidx_filename "CADIS/mnist/unbalanced_cluster10/100client" --num_rounds 3000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=2 python main.py --task mnist_cnn_PA0.3_N100_K10_NEW --model cnn --algorithm fedavg --wandb 1 --data_folder "./benchmark/mnist/data" --log_folder "fedtask" --dataidx_filename "CADIS/mnist/pareto_0.3/100client" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=2 python main.py --task mnist_cnn_PA1_N100_K10_NEW --model cnn --algorithm fedavg --wandb 1 --data_folder "./benchmark/mnist/data" --log_folder "fedtask" --dataidx_filename "CADIS/mnist/pareto_1/100client" --num_rounds 3000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=2 python main.py --task cifar10_cnn_PA0.6_N100_K10_NEW --model cnn --algorithm fedavg --wandb 1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "CADIS/cifar10/pareto_0.6/100client" --num_rounds 3000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=2 python main.py --task emnist_cnn_PA0.4_N100_K10_NEW --model cnn --algorithm fedavg --wandb 1 --data_folder "./benchmark/emnist/data" --log_folder "fedtask" --dataidx_filename "CADIS/emnist/pareto_0.4/100client" --num_rounds 3000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 1 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=2 python main.py --task cifar100_quantitative_N100_K10 --model resnet9 --algorithm fedavg --wandb 1 --data_folder "./benchmark/cifar100/data" --log_folder "fedtask" --dataidx_filename "CADIS/cifar100/quantitative" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=1 python main.py --task cifar100_PA_0.5_N100_K10 --model resnet9 --algorithm fedavg --wandb 1 --data_folder "./benchmark/cifar100/data" --log_folder "fedtask" --dataidx_filename "CADIS/cifar100/pareto2_0.5/100client" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
