# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N10_K10 --wandb 0 --model cnn --algorithm mp_fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/10client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N10_K10 --wandb 0 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/10client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N10_K10 --wandb 0 --model cnn --algorithm mp_proposal --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/10client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N20_K20 --wandb 0 --model cnn --algorithm mp_fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/20client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N20_K20 --wandb 0 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/20client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N20_K20 --wandb 0 --model cnn --algorithm mp_proposal --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/20client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N30_K30 --wandb 0 --model cnn --algorithm mp_fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/30client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N30_K30 --wandb 0 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/30client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_iid_N30_K30 --wandb 0 --model cnn --algorithm mp_proposal --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/iid/30client/mnist_iid.json --num_rounds 200 --num_epochs 1 --proportion 1 --batch_size 8 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
