mkdir fedtask

CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_cluster_rich_N50_K10 --wandb 0 --model cnn --algorithm mp_fedfsl-mi-adv --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/cluster_rich/50client/mnist_rich.json --num_rounds 250 --num_epochs 4 --proportion 1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_cluster_rich_N50_K10 --wandb 1 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/cluster_rich/50client/mnist_rich.json --num_rounds 250 --num_epochs 4 --proportion 1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_cluster_sparse_N50_K10 --wandb 1 --model cnn --algorithm fedfsl-mi-adv --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/cluster_sparse/50client/mnist_sparse.json --num_rounds 250 --num_epochs 4 --proportion 1 --batch_size 2 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_cluster_sparse_N50_K10 --wandb 1 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/cluster_sparse/50client/mnist_sparse.json --num_rounds 250 --num_epochs 4 --proportion 1 --batch_size 2 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_sparse_N10_K10 --wandb 0 --model cnn --algorithm mp_fedkdr --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/sparse/10client/mnist_sparse.json --num_rounds 500 --num_epochs 4 --proportion 1 --batch_size 2 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
