# Discription: https://docs.google.com/spreadsheets/d/1km7c9OhhGL3uk9GvVaJw5bEC0Fg3kAPb4meb6Y96MjU

mkdir -p motiv/mnist

# Pareto N=100, K=10

# Epochs = 1, R = 5000
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E1 --model cnn --algorithm scaffold --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 5000 --num_epochs 1 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E1 --model cnn --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 5000 --num_epochs 1 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E1 --model cnn --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 5000 --num_epochs 1 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Epochs = 5, R = 1000
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E5 --model cnn --algorithm scaffold --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E5 --model cnn --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E5 --model cnn --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 1000 --num_epochs 5 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Epochs = 10, R = 500
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E10 --model cnn --algorithm scaffold --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 10 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E10 --model cnn --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 10 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E10 --model cnn --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 500 --num_epochs 10 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Epochs = 20, R = 250
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E20 --model cnn --algorithm scaffold --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 250 --num_epochs 20 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E20 --model cnn --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 250 --num_epochs 20 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E20 --model cnn --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 250 --num_epochs 20 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Epochs = 25, R = 200
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E25 --model cnn --algorithm scaffold --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 200 --num_epochs 25 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E25 --model cnn --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 200 --num_epochs 25 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E25 --model cnn --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 200 --num_epochs 25 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Epochs = 40, R = 125
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E40 --model cnn --algorithm scaffold --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 125 --num_epochs 40 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E40 --model cnn --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 125 --num_epochs 40 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E40 --model cnn --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 125 --num_epochs 40 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Epochs = 50, R = 100
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E50 --model cnn --algorithm scaffold --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 100 --num_epochs 50 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E50 --model cnn --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 100 --num_epochs 50 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K10_E50 --model cnn --algorithm mp_proposal --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 100 --num_epochs 50 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0

# Single set R = 5000
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_singleset --model cnn --algorithm singleset --wandb 0 --data_folder "./benchmark/mnist/data" --log_folder "motiv/mnist" --dataidx_filename "mnist/100client/pareto/MNIST-noniid-pareto_1.json" --num_rounds 5000 --num_epochs 1 --proportion 0.1 --batch_size 16 --num_threads_per_gpu 1  --num_gpus 2 --server_gpu_id 0
