# For CIFAR10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --kd_fct 2 --algorithm fedsdiv_tranS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --kd_fct 4 --algorithm fedsdiv_tranS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --kd_fct 6 --algorithm fedsdiv_tranS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --kd_fct 8 --algorithm fedsdiv_tranS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --kd_fct 10 --algorithm fedsdiv_tranS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --kd_fct 2 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --kd_fct 4 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --kd_fct 6 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --kd_fct 8 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --kd_fct 10 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --kd_fct 2 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --kd_fct 4 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --kd_fct 6 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --kd_fct 8 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --kd_fct 10 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --kd_fct 2 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --kd_fct 4 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --kd_fct 6 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --kd_fct 8 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --kd_fct 10 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_pareto_N10_K10 --model resnet9 --kd_fct 2 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_pareto.json" --num_rounds 500 --num_epochs 5  --proportion 1 --batch_size 8  --num_threads_per_gpu 1  --num_gpus 1 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_pareto_N10_K10 --model resnet9 --kd_fct 4 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_pareto.json" --num_rounds 500 --num_epochs 5  --proportion 1 --batch_size 8  --num_threads_per_gpu 1  --num_gpus 1 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_pareto_N10_K10 --model resnet9 --kd_fct 6 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_pareto.json" --num_rounds 500 --num_epochs 5  --proportion 1 --batch_size 8  --num_threads_per_gpu 1  --num_gpus 1 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_pareto_N10_K10 --model resnet9 --kd_fct 8 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_pareto.json" --num_rounds 500 --num_epochs 5  --proportion 1 --batch_size 8  --num_threads_per_gpu 1  --num_gpus 1 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_pareto_N10_K10 --model resnet9 --kd_fct 10 --algorithm fedsdiv_transS --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_pareto.json" --num_rounds 500 --num_epochs 5  --proportion 1 --batch_size 8  --num_threads_per_gpu 1  --num_gpus 1 --server_gpu_id 0


# For CIFAR 100

