# mnist_pareto_N10_K10
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 1 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 2 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 3 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 4 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 5 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 6 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 7 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 8 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 9 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 10 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_clustered_N100_K20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 1 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 2 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 3 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 4 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 5 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 6 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 7 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 8 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 9 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --neg_fct 1 --neg_mrg 10 --temp 1 --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
